name: Deploy NestJS to EC2 (Free Tier)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "20"

    # 3. Install dependencies (repo root)
    - name: Install dependencies
      run: npm install

    # 4. Build NestJS
    - name: Build NestJS
      run: npm run build

    # 5. Upload dist to EC2
    - name: Upload dist folder to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dist/**"
        target: "${{ secrets.EC2_APP_DIR }}"

    # 6. Upload root-level backend files
    - name: Upload config files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./*"
        target: ${{ secrets.EC2_APP_DIR }}

        # DEBUG 1: Check key length
    - name: Debug Key length
      run: echo "${{ secrets.EC2_SSH_KEY }}" | wc -c

    # DEBUG 2: Check if GitHub is masking the key
    - name: Debug First line masked?
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | head -n 1 | sed 's/./*/g'

    # DEBUG 3: Look for CRLF or weird chars
    - name: Debug CRLF check
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | sed -n l


    - name: Restart backend on EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "DEBUG SSH WORKS"



